title: <p align="center"> Shashi Khurana </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="#">Resume</a> |
  <a href="https://www.linkedin.com/in/shashi-khurana-1a138513/">LinkedIn</a> |
  <a href="https://github.com/sbkhuran">GitHub</a>
  
  <br>   
  DataScience evangelist and Strategic Architect with 22 years of rich
  experience in building highly scalable enterprise level applications. Organized and dependable candidate successful
  at managing multiple priorities with a positive attitude. Decisive, result oriented, enthusiastic IT professional motivated by challenging
  projects and extreme deadlines with leadership experience in technology and AI/ML development background. 
  <br>
  </p>
theme: jekyll-theme-minimal
