title: <p align="center"> Shashi Khurana </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shashi-khurana-1a138513/">LinkedIn</a> |
  <a href="https://github.com/sbkhuran">GitHub</a>
  
  <br>   
  Technology evangelist and Strategic Architect with 20 years of rich
<<<<<<< HEAD
  experience in building highly scalable enterprise level software and
  web applications. Organized and dependable candidate successful
  at managing multiple priorities with a positive attitude. Willingness to
  take on added responsibilities to meet team goals. Decisive, result oriented, enthusiastic IT professional motivated by challenging
  projects and extreme deadlines with leadership experience in technology and business development background. 
=======
experience in building highly scalable enterprise level software and
web applications. Organized and dependable candidate successful
at managing multiple priorities with a positive attitude. Willingness to
take on added responsibilities to meet team goals. Decisive, result oriented, enthusiastic IT professional motivated by challenging
projects and extreme deadlines with leadership experience in technology and business development background. 
>>>>>>> df1f9071fd733217725e7bed502b415fade05d51
  <br>
  </p>
theme: jekyll-theme-minimal
